### ISSUE TITLE
AttributeError: module 'plot' has no attribute 'plot_mirror'

### ISSUE THREAD

**Issue by YUANMY2021** [bittremieux/cosine_neutral_loss#6]
When I running the demo py pipline:

I got the followings:

Traceback (most recent call last):
  File "/public/home/yuanmy/cosine_neutral_loss-main/test_plot.py", line 30, in <module>
    plot.plot_mirror(spectrum1, spectrum2, score, filename)
AttributeError: module 'plot' has no attribute 'plot_mirror'

Is the plot_mirror function written in anywhere?

**Comment by bittremieux** [comment]
[`plot_mirror` is available in `plot`](https://github.com/bittremieux/cosine_neutral_loss/blob/main/src/plot.py#L19). You might be importing a different plot module instead. You can do `plot.__file__` to figure out where your plot module comes from.

**Comment by YUANMY2021** [comment]
Could you please help me modify my script  for 2 mgf files plot:

import matchms as ms
import plot
from matchms import importing as mi
from matchms import filtering as mf
import spectrum_utils


query_spectra = mi.load_from_mgf("./ceshi.txt")
db_spectra = mi.load_from_mgf("./ceshi2.txt")


def peak_processing(spectrum):
    spectrum = mf.default_filters(spectrum)
    spectrum = mf.normalize_intensities(spectrum)
    spectrum = mf.select_by_intensity(spectrum, intensity_from=0.01)
    spectrum = mf.select_by_mz(spectrum, mz_from=10, mz_to=1000)
    return spectrum


spectrum1 = [peak_processing(s) for s in query_spectra]
spectrum2 = [peak_processing(s) for s in db_spectra]


for score, filename in [
    (None, "spectra.png"),
    ("cosine", "cosine.png"),
    ("modified_cosine", "modified_cosine.png"),
    ("neutral_loss", "neutral_loss.png"),
]:
    plot.plot_mirror(spectrum1, spectrum2, score, filename)

**Comment by bittremieux** [comment]
I haven't used matchms a lot, so I can't immediately help you with that. This analysis uses [spectrum_utils](https://github.com/bittremieux/spectrum_utils/) to process and plot spectra.

spectrum_utils includes various spectrum processing functionality to scale intensities, remove low-intensity noise peaks, etc., similar to what you're doing. It also includes high-level plotting functionality. For consistency it might be more convenient to try to do all of your steps using spectrum_utils instead.

So an initial problem is that your spectra are objects from matchms, whereas the code expects objects from spectrum_utils. There might be a few other issues as well. For example `spectrum1` and `spectrum2` seem to be lists, rather than individual spectra.
