### ISSUE TITLE
Cosine similarity discrepancies between your method and SciPy

### ISSUE THREAD

**Issue by ddomingof** [bittremieux/cosine_neutral_loss#7]
Hi @bittremieux ,

We were reproducing your results and noticed that the scores of the (unmodified) cosine similarity method are a bit off compared to the [SciPy method](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html) (1 - distance, which should be the same than [cosine similarity](https://github.com/bittremieux/cosine_neutral_loss/blob/afc6447a96f10e27a1965e6ea701c42f8afaa223/src/similarity.py#L30)). 
![image](https://github.com/bittremieux/cosine_neutral_loss/assets/15685795/def7c0ae-bdcc-4bb5-a889-a0b90c12d95e).

Below is a plot of the cosine similarities using a subset of your data in this [notebook](https://github.com/bittremieux/cosine_neutral_loss/blob/main/notebooks/gnps_libraries.ipynb) using your method and SciPy's (used by [YuanYue](https://github.com/YuanyueLi/SpectralEntropy) in his benchmark of [spectral similarity metrics](https://www.nature.com/articles/s41592-021-01331-z)), which yield a correlation of 0.94. We would expect it to have a correlation of 1.

We used the function below to transform the MSMSSpectum() class to NumPy vector to use the SciPy method. 

```
def create_vector(spectra1, spectra2):

    vector1 = []
    vector2 = []

    common_mzs = np.union1d(spectra1.mz, spectra2.mz)

    for mz in common_mzs:

        # check if they are in both spectra
        if mz in spectra1.mz:
            vector1.append(spectra1.intensity[spectra1.mz == mz][0])
        else:
            vector1.append(0)
        
        if mz in spectra2.mz:
            vector2.append(spectra2.intensity[spectra2.mz == mz][0])
        else:
            vector2.append(0)
    
    return np.array(vector1, dtype=np.float32), np.array(vector2, dtype=np.float32)

# We basically add this snippet to your notebook to make the comparison
for spectra1, spectra2 in tqdm(itt.combinations(spectra, 2), total=len(spectra) * (len(spectra) - 1) / 2):

    vector1, vector2 = create_vector(spectra1, spectra2)

    cosine1 = 1 - cosine_distance(vector1, vector2)
    cosine2 = similarity.cosine(spectra1, spectra2, fragment_mz_tolerance=0.1).score

```

Do you notice something off in our method that could explain the differences?

Thanks for the help!

**Comment by ddomingof** [comment]
Adding to the previous message, the scores are also different than the matchms implementation
<img width="983" alt="Screenshot 2023-07-17 at 21 08 09" src="https://github.com/bittremieux/cosine_neutral_loss/assets/15685795/740569f7-cdf9-4a78-b98d-3b5e9948c77e">

**Comment by bittremieux** [comment]
I don't convert spectra to vectors, but instead use a "peak-by-peak" implementation of the cosine similarity. This means that I loop through both spectra and check for pairs of matching peaks when they are within the fragment m/z tolerance of each other. This avoids edge effects due to binning, where a fragment can be assigned to a neighboring bin due to the measurement error and incorrectly lead to a lower cosine similarity. (Note that in your plots my cosine similarities are generally higher than the vectorized ones, as expected).

The peak-to-peak implementation is more complex and slightly slower (essentially using the Hungarian algorithm to ensure unique peak matches), which is why SciPy/YuanYue/matchms use the simple solution. However, my version should give slightly superior similarities. matchms also has an implementation of the cosine similarity using the Hungarian algorithm, which should give the same results as my code. (Although the code here should be faster, or at least, it was.)

See the [implementation](https://github.com/bittremieux/cosine_neutral_loss/blob/main/src/similarity.py#L210) for the specific details.
